# Generated by Django 2.2.7 on 2019-11-13 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('ingredient_calories', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('veg', models.BooleanField()),
                ('breakfast', models.BooleanField()),
                ('lunch', models.BooleanField()),
                ('dinner', models.BooleanField()),
                ('snacks', models.BooleanField()),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('meal_method', models.CharField(max_length=2000000)),
                ('meal_carbs', models.IntegerField(blank=True, null=True)),
                ('meal_protein', models.IntegerField(blank=True, null=True)),
                ('meal_fat', models.IntegerField(blank=True, null=True)),
                ('meal_calories', models.IntegerField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(related_name='ingredientName', to='Dietplan.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Dietplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietplan_name', models.CharField(max_length=255, null=True)),
                ('calories_slab', models.IntegerField(blank=True, null=True)),
                ('breakfast', models.ManyToManyField(related_name='db', to='Dietplan.Meal')),
                ('dinner', models.ManyToManyField(related_name='dd', to='Dietplan.Meal')),
                ('lunch', models.ManyToManyField(related_name='dl', to='Dietplan.Meal')),
                ('snacks1', models.ManyToManyField(related_name='s1', to='Dietplan.Meal')),
                ('snacks2', models.ManyToManyField(related_name='s2', to='Dietplan.Meal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
