# Generated by Django 2.2.7 on 2019-11-13 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('goal_weight', models.FloatField(null=True)),
                ('goal_time_period', models.IntegerField(null=True)),
                ('job', models.CharField(max_length=255)),
                ('bmi', models.IntegerField(null=True)),
                ('total_calories', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('goal_weight', models.FloatField(null=True)),
                ('goal_time_period', models.IntegerField(null=True)),
                ('job', models.CharField(max_length=255)),
                ('bmi', models.IntegerField(null=True)),
                ('total_calories', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
